# Generated by Django 5.2 on 2025-04-24 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecard',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_cards', to='portfolio_front.servicesection'),
        ),
    ]
