# Generated by Django 5.2 on 2025-04-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_front', '0003_testimonial_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='iframe_url',
            field=models.TextField(default=''),
        ),
    ]
